<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MySqlConnector" Version="2.2.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Super.Core\Super.Core.csproj" />
    <ProjectReference Include="..\Super.Dapper\Super.Dapper.csproj" />
  </ItemGroup>

</Project>